fix(classifier): Use the self's `super` for initialise
This means that the attributes are properly set on the model.

I recreated the error by downloading the existing model:

```shell
$ aws s3 cp --profile production s3://cpr-prod-models/Q956/RulesBasedClassifier/v3/model.pickle q956-rules-v3-model.pickle
download: s3://cpr-prod-models/Q956/RulesBasedClassifier/v3/model.pickle to ./q956-rules-v3-model.pickle
$ poetry run python
Python 3.10.14 (main, Jul 25 2024, 22:56:04) [Clang 18.1.8 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> local_classifier_path = "./q956-rules-v3-model.pickle"
>>> from src.classifier import Classifier
>>> classifier = Classifier.load(local_classifier_path)
>>> classifier.predict("Test")
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ /Users/jesse/src/github.com/climatepolicyradar/knowledge-graph/src/classifier/rules_based.py:50  │
│ in predict                                                                                       │
│                                                                                                  │
│   47 │                                                                                           │
│   48 │   def predict(self, text: str) -> list[Span]:                                             │
│   49 │   │   """Predict whether the supplied text contains an instance of the concept."""        │
│ ❱ 50 │   │   positive_matches = self.positive_matcher.predict(text)                              │
│   51 │   │   negative_matches = (                                                                │
│   52 │   │   │   self.negative_matcher.predict(text) if self.negative_matcher else []            │
│   53 │   │   )                                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'RulesBasedClassifier' object has no attribute 'positive_matcher'
```

After re-training locally, with `just train Q956`, I repeated the
steps above, and I didn't get the error.

Using the new script, I updated the model artifacts:

```
$ AWS_REGION=eu-west-1 poetry run deploy new --to-aws-env staging --wikibase-ids Q956 --no-get
..
$ AWS_REGION=eu-west-1 poetry run deploy existing --from-aws-env staging --to-aws-env production --no-get
```

FIXES PLA-380