fix: Make task hashable
I saw this a lot[^1][^2] and it created a lot of noise, and may also cause
actual problems. I don't think the latter would be true though, as we
don't use cached results, explicitly at least.

TOWARDS PLA-658

[^1]:
```
Error encountered when computing cache key - result will not be persisted.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/cache_policies.py", line 374, in compute_key
    return hash_objects(hashed_inputs, raise_on_failure=True)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/hashing.py", line 89, in hash_objects
    raise HashError(msg)
prefect.exceptions.HashError: Unable to create hash - objects could not be serialized.
  JSON error: Unable to serialize unknown type: <class 'aioboto3.session.Session'>
  Pickle error: cannot pickle '_asyncio.Task' object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/task_engine.py", line 169, in compute_transaction_key
    key = self.task.cache_policy.compute_key(
  File "/usr/local/lib/python3.10/site-packages/prefect/cache_policies.py", line 214, in compute_key
    policy_key = policy.compute_key(
  File "/usr/local/lib/python3.10/site-packages/prefect/cache_policies.py", line 384, in compute_key
    raise ValueError(msg) from exc
ValueError: Unable to create hash - objects could not be serialized.
  JSON error: Unable to serialize unknown type: <class 'aioboto3.session.Session'>
  Pickle error: cannot pickle '_asyncio.Task' object

This often occurs when task inputs contain objects that cannot be cached like locks, file handles, or other system resources.

To resolve this, you can:
  1. Exclude these arguments by defining a custom `cache_key_fn`
  2. Disable caching by passing `cache_policy=NO_CACHE`
```
[^2]: https://app.prefect.cloud/account/4b1558a0-3c61-4849-8b18-3e97e0516d78/workspace/1753b4f0-6221-4f6a-9233-b146518b4545/runs/flow-run/0684fda2-449e-7cdb-8000-732e3b78df1a?entity_id=0684fdc6-8809-7f22-8000-928b99be820a